class Addtrips < ActiveRecord::Migration
  def up
	ListItem.create(title: "Sep. 10, 2011", content: "Point Dume climbing day trip with the Climbing Club")
	ListItem.create(title: "Sep. 17, 2011", content: "Malibu Creek climbing day trip with Sean")
	ListItem.create(title: "Sep. 18, 2011", content: "Co-guide - Malibu Creek climbing day trip with SC Outfitters")
	ListItem.create(title: "Sep. 25, 2011", content: "Malibu Creek climbing day trip with Climbing Club")
	ListItem.create(title: "Oct. 15, 2011", content: "Epic at Malibu Creek with Chris")
	ListItem.create(title: "Oct. 22-23, 2011", content: "Lead guide - Holcomb Valley climbing overnight with SC Outfitters")
	ListItem.create(title: "Nov. 3, 2011", content: "Learning trad at Joshua Tree with Simon")
	ListItem.create(title: "Nov. 5, 2011", content: "Lead guide - Malibu Creek climbing day trip with SC Outfitters")
	ListItem.create(title: "Nov 12-13, 2011", content: "Lead guide - New Jack City climbing overnight with Climbing Club")
	ListItem.create(title: "Nov. 19-20, 2011", content: "Overnight trip to Alabama Hills with friends")
	ListItem.create(title: "Dec. 3-4, 2011", content: "Bishop bouldering overnight with friends")
	ListItem.create(title: "Jan. 2-3, 2012", content: "Opal Creek Backpacking")
	ListItem.create(title: "Jan. 8, 2012", content: "Lead guide - Echo Cliffs with SC Outfitters")
	ListItem.create(title: "Jan. 13-16, 2012", content: "Big Sur Backpacking with SC Outfitters")
	ListItem.create(title: "Jan. 22, 2012", content: "Co-guide - Point Dume with the Climbing Club")
	ListItem.create(title: "Jan. 28, 2012", content: "The Lookout climbing day trip with Sean")
	ListItem.create(title: "Jan. 29, 2012", content: "Co-guide - Joshua Tree climbing day trip with SC Outfitters")
	ListItem.create(title: "Feb. 4-5, 2012", content: "WFA Training with SC Outfitters")
	ListItem.create(title: "Feb. 11-12, 2012", content: "Lead guide - New Jack City climbing overnight with SC Outfitters")
	ListItem.create(title: "Feb. 17-20, 2012", content: "Co-guide - Kern River Basin Backpacking trip with SC Outfitters")
	ListItem.create(title: "Feb. 25, 2012", content: "Echo Cliffs climbing day trip with Kyle and Simon")
	ListItem.create(title: "Mar. 3, 2012", content: "Echo Cliffs climbing day trip with climbing club")
	ListItem.create(title: "Mar. 4, 2012", content: "Lead guide - Pt. Dume climbing day trip with residence hall")
	ListItem.create(title: "Mar. 30 - Apr. 1, 2012", content: "Lead guide - Silver Peak backpacking with SC Outfitters")
	ListItem.create(title: "Apr. 6, 2012", content: "Malibu Creek climbing day trip with friends")
	ListItem.create(title: "Apr. 14-15, 2012", content: "Joshua Tree climbing overnight with Simon")
	ListItem.create(title: "Apr. 26, 2012", content: "Riverside Quarry climbing day trip with Simon")
	ListItem.create(title: "May 4-5, 2012", content: "Willett Hot Springs backpacking overnight")
	ListItem.create(title: "May 6, 2012", content: "Malibu Creek climbing day trip with Sean")
	ListItem.create(title: "May 12-13, 2012", content: "Spring skiing and an overnight stay at Silcox Hut")
	ListItem.create(title: "May 26, 2012", content: "Summit attempt on Mt. Hood")
	ListItem.create(title: "May 29-31, 2012", content: "Backpacking the Tanner Butte-Eagle Creek Loop with friends")
	ListItem.create(title: "June 4-13, 2012", content: "WFR Certification")
	ListItem.create(title: "June 16-20, 2012", content: "Overnight climbing trip to Smith Rock with Kyle and Matt")
	ListItem.create(title: "July 7, 2012", content: "Adventurous Young Mazamas (AYM) Hike in Bull of The Woods")
	ListItem.create(title: "July 16-18, 2012", content: "Solo backpacking: Eagle Creek - Wahtum Lake - Ruckel Creek")
	ListItem.create(title: "July 28 - August 5, 2012", content: "Explorer Post 58 Canada Expedition")
	ListItem.create(title: "August 9-10, 2012", content: "Siouxon Creek Backpacking")
	ListItem.create(title: "August 18-19, 2012", content: "Overnight climbing trip to Smith Rock with Matt")
	ListItem.create(title: "August 22-26, 2012", content: "100 Mile PCT Segment Hike - Mt. Adams to Timberline Lodge")
	ListItem.create(title: "September 7- 9, 2012", content: "Silver Falls retreat with LC Outdoor Pursuits")
	ListItem.create(title: "September 14-16, 2012", content: "Assistant Leader - Waldo Lake Sea Kayaking with LC College Outdoors")
	ListItem.create(title: "September 28-29, 2012", content: "Climbing overnight to Smith with friends")
	ListItem.create(title: "October 11-13, 2012", content: "Gorge backpacking Herman Creek")
	ListItem.create(title: "October 19-21, 2012", content: "Climbing overnight to Smith with friends")
	ListItem.create(title: "November 16-18, 2012", content: "Climbing overnight to Smith with friends")
	ListItem.create(title: "December 27-28, 2012", content: "Climbing overnight to Smith with Matt")
	ListItem.create(title: "January 3-4, 2012", content: "XC Skiing overnight in the Willamette Pass region")
	ListItem.create(title: "January 17-20, 2013", content: "Winter Skills Clinic with LC College Outdoors")
	ListItem.create(title: "February 9, 2013", content: "Ape Caves scout trip with LC College Outdoors")
	ListItem.create(title: "February 16, 2013", content: "OSU VertFest Climbing Competition")
	ListItem.create(title: "February 17, 2013", content: "Assistant Leader for XC Skiing with LC College Outdoors")
	ListItem.create(title: "February 22-24, 2013", content: "Climbing overnight to Smith with friends")
	ListItem.create(title: "March 2-3, 2013", content: "Assistant Leader for Winter Camping Clinic with LC College Outdoors")
	ListItem.create(title: "March 8-9, 2013", content: "Assistant Leader for Outdoor Pursuits Floor spring retreat")
	ListItem.create(title: "March 15-16, 2013", content: "Climbing Monkey Face at Smith")
	ListItem.create(title: "March 23-25, 2013", content: "Backpacking the Lower Deschutes")
	ListItem.create(title: "March 25-27, 2013", content: "Rock Climbing trip to Smith Rocks")
	ListItem.create(title: "March 28, 2013", content: "Mountain Biking around Waldo Lake")
	ListItem.create(title: "May 17-19, 2013", content: "Smith Rock with friends")
	ListItem.create(title: "June 8, 2013", content: "Climbing Mt. Adams")
	ListItem.create(title: "June 15, 2013", content: "Climbing Mt. Hood")
  end

  def down
  end
end
